server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://172.31.18.6:3306/sendkar
    username: sendkar
    password: Password123!
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: "true"
    validationQuery: SELECT 1
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

    jpa:
      show-sql: "true"
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: "false"
      time-zone: UTC

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: "604800000"

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket: sendkar-file-bucket-poc
    region: ap-south-1
  sns:
    senderid: sendkar
    region: ap-southeast-1