server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sendkar
    username: mysqluser
    password: Password123!
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: "true"
    validationQuery: SELECT 1

  jpa:
    show-sql: "true"
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: "false"
    time-zone: UTC

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: "604800000"
